---
name: "kube"
version: "0.1.0"
usage: "helm kube [list|wildcard]"
description: |-
  Enter kubernetes container.
command: "$HELM_PLUGIN_DIR/run.sh"
hooks:
  install: "$HELM_PLUGIN_DIR/run.sh --help"
